server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-usuarios
  cloud:
    compatibility-verifier:
      enabled: false
    inetutils:
      preferred-networks:
        - 10.0
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: dd140621-3398-4bfe-805b-9c162df51706
        credential:
          client-id: cb8b1711-d599-4a45-94d9-9251f15db61a
        app-id-uri: api://cb8b1711-d599-4a45-94d9-9251f15db61a

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always